In [7]:
import pandas as pd 
import numpy as np

In [ ]:
how to create series on pandas

In [8]:
s= pd.Series([1, 3, 5, np.nan, 6,8]) 
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [ ]:
pandas date k function k liye bhee use hotee hai

In [9]:
dates = pd.date_range("20130101",periods=15) 
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06', '2013-01-07', '2013-01-08',
               '2013-01-09', '2013-01-10', '2013-01-11', '2013-01-12',
               '2013-01-13', '2013-01-14', '2013-01-15'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
pandas k andr hum numpy librari use kar rahey hai jis mey random ly k arahey mtlb range k andr joo number hoo

In [10]:
df = pd.DataFrame(np.random.rand(15, 5), index=dates, columns=list("abcd ")) 
df

                   a         b         c         d
2013-01-01  0.528447  0.308543  0.012169  0.726910  0.982063
2013-01-02  0.355721  0.213612  0.792436  0.223574  0.435250
2013-01-03  0.747099  0.276038  0.035750  0.786583  0.821242
2013-01-04  0.853518  0.751510  0.308997  0.144952  0.203816
2013-01-05  0.836874  0.202672  0.172160  0.139893  0.165972
2013-01-06  0.186474  0.889345  0.969984  0.175003  0.074074
2013-01-07  0.014540  0.213853  0.477574  0.681488  0.341422
2013-01-08  0.356723  0.727271  0.251049  0.338078  0.719103
2013-01-09  0.167650  0.359722  0.193021  0.318813  0.990212
2013-01-10  0.639777  0.656659  0.149285  0.221727  0.360613
2013-01-11  0.781557  0.045166  0.347977  0.997130  0.085154
2013-01-12  0.994200  0.256909  0.133926  0.852704  0.421368
2013-01-13  0.429919  0.780033  0.391373  0.183233  0.405522
2013-01-14  0.619666  0.550595  0.313288  0.356660  0.729637
2013-01-15  0.629908  0.961563  0.001321  0.090288  0.234901

In [ ]:
# what is dictionary

In [11]:
dict = {"cyrus": 6.0, "aloo": 5.5}

In [12]:
df2 = pd.DataFrame({"A": 1.0,
                    "B": pd.Timestamp("20130102"),
                    "C": pd.Series(1, index=list(range(4)), dtype="float32"),
                    "D":np.array([3] * 4, dtype="int32"),
                    "E": pd.Categorical(["test", "train", "test","train"]),
                    "F":"foo",})

In [13]:
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [ ]:
check types

In [14]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [ ]:
es command sy bhee hum eskoo check kar saqtey hai

In [15]:
df2.info

<bound method DataFrame.info of      A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo>

In [ ]:
Data view kaisey kartey hai

In [ ]:
df.head() aur df.tail()

In [18]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06', '2013-01-07', '2013-01-08',
               '2013-01-09', '2013-01-10', '2013-01-11', '2013-01-12',
               '2013-01-13', '2013-01-14', '2013-01-15'],
              dtype='datetime64[ns]', freq='D')

In [19]:
df.columns

Index(['a', 'b', 'c', 'd', ' '], dtype='object')

In [20]:
df

                   a         b         c         d
2013-01-01  0.528447  0.308543  0.012169  0.726910  0.982063
2013-01-02  0.355721  0.213612  0.792436  0.223574  0.435250
2013-01-03  0.747099  0.276038  0.035750  0.786583  0.821242
2013-01-04  0.853518  0.751510  0.308997  0.144952  0.203816
2013-01-05  0.836874  0.202672  0.172160  0.139893  0.165972
2013-01-06  0.186474  0.889345  0.969984  0.175003  0.074074
2013-01-07  0.014540  0.213853  0.477574  0.681488  0.341422
2013-01-08  0.356723  0.727271  0.251049  0.338078  0.719103
2013-01-09  0.167650  0.359722  0.193021  0.318813  0.990212
2013-01-10  0.639777  0.656659  0.149285  0.221727  0.360613
2013-01-11  0.781557  0.045166  0.347977  0.997130  0.085154
2013-01-12  0.994200  0.256909  0.133926  0.852704  0.421368
2013-01-13  0.429919  0.780033  0.391373  0.183233  0.405522
2013-01-14  0.619666  0.550595  0.313288  0.356660  0.729637
2013-01-15  0.629908  0.961563  0.001321  0.090288  0.234901

In [ ]:
array k andr index aur head nai hotey ye nichey double dimenstional data bn giya hai 
row aurf coulmns sy, array bn giya hai, numpy k andr convert kar diya

In [21]:
df.to_numpy()

array([[0.52844737, 0.3085429 , 0.0121688 , 0.72690996, 0.98206324],
       [0.35572101, 0.21361235, 0.79243631, 0.22357355, 0.43524976],
       [0.74709873, 0.27603774, 0.03574965, 0.78658296, 0.82124241],
       [0.85351802, 0.7515097 , 0.30899656, 0.14495181, 0.20381604],
       [0.83687357, 0.20267198, 0.17215957, 0.13989291, 0.16597207],
       [0.18647431, 0.88934485, 0.96998375, 0.17500342, 0.07407371],
       [0.01454026, 0.21385349, 0.4775739 , 0.68148787, 0.34142241],
       [0.35672268, 0.72727083, 0.25104938, 0.33807762, 0.71910282],
       [0.16764982, 0.35972182, 0.19302103, 0.31881314, 0.99021217],
       [0.63977692, 0.65665915, 0.14928527, 0.22172659, 0.36061301],
       [0.78155673, 0.04516569, 0.3479765 , 0.99712981, 0.08515428],
       [0.99420021, 0.2569086 , 0.13392556, 0.85270408, 0.42136772],
       [0.42991892, 0.78003331, 0.39137285, 0.18323296, 0.40552169],
       [0.61966648, 0.55059468, 0.31328839, 0.3566602 , 0.72963695],
       [0.62990772, 0.96156337, 0.00132097, 0.09028799, 0.23490117]])

In [22]:
df.describe()

               a          b          c          d
count  15.000000  15.000000  15.000000  15.000000  15.000000
mean    0.542805   0.479566   0.303354   0.415802   0.464690
std     0.285077   0.293204   0.274644   0.304110   0.309941
min     0.014540   0.045166   0.001321   0.090288   0.074074
25%     0.356222   0.235381   0.141605   0.179118   0.219359
50%     0.619666   0.359722   0.251049   0.318813   0.405522
75%     0.764328   0.739390   0.369675   0.704199   0.724370
max     0.994200   0.961563   0.969984   0.997130   0.990212

In [23]:
df

                   a         b         c         d
2013-01-01  0.528447  0.308543  0.012169  0.726910  0.982063
2013-01-02  0.355721  0.213612  0.792436  0.223574  0.435250
2013-01-03  0.747099  0.276038  0.035750  0.786583  0.821242
2013-01-04  0.853518  0.751510  0.308997  0.144952  0.203816
2013-01-05  0.836874  0.202672  0.172160  0.139893  0.165972
2013-01-06  0.186474  0.889345  0.969984  0.175003  0.074074
2013-01-07  0.014540  0.213853  0.477574  0.681488  0.341422
2013-01-08  0.356723  0.727271  0.251049  0.338078  0.719103
2013-01-09  0.167650  0.359722  0.193021  0.318813  0.990212
2013-01-10  0.639777  0.656659  0.149285  0.221727  0.360613
2013-01-11  0.781557  0.045166  0.347977  0.997130  0.085154
2013-01-12  0.994200  0.256909  0.133926  0.852704  0.421368
2013-01-13  0.429919  0.780033  0.391373  0.183233  0.405522
2013-01-14  0.619666  0.550595  0.313288  0.356660  0.729637
2013-01-15  0.629908  0.961563  0.001321  0.090288  0.234901

In [ ]:
uper waley data koo transpose karna mtlb k rows koo column mey convert karna 
hai aur columns koo row mey convert karna hai

In [24]:
df.T

,2013-01-01,2013-01-02,2013-01-03,2013-01-04,2013-01-05,2013-01-06,2013-01-07,2013-01-08,2013-01-09,2013-01-10,2013-01-11,2013-01-12,2013-01-13,2013-01-14,2013-01-15
a,0.528447,0.355721,0.747099,0.853518,0.836874,0.186474,0.014540,0.356723,0.167650,0.639777,0.781557,0.994200,0.429919,0.619666,0.629908
b,0.308543,0.213612,0.276038,0.751510,0.202672,0.889345,0.213853,0.727271,0.359722,0.656659,0.045166,0.256909,0.780033,0.550595,0.961563
c,0.012169,0.792436,0.035750,0.308997,0.172160,0.969984,0.477574,0.251049,0.193021,0.149285,0.347977,0.133926,0.391373,0.313288,0.001321
d,0.726910,0.223574,0.786583,0.144952,0.139893,0.175003,0.681488,0.338078,0.318813,0.221727,0.997130,0.852704,0.183233,0.356660,0.090288
,0.982063,0.435250,0.821242,0.203816,0.165972,0.074074,0.341422,0.719103,0.990212,0.360613,0.085154,0.421368,0.405522,0.729637,0.234901

In [ ]:
agr axis=1 hoo ga mtlb hum column bna rahey hai aur agr axis=0 hoo ga mtlb hum rows bna rahen hai

In [26]:
df.sort_index(axis=1, ascending=False)

                   d         c         b         a
2013-01-01  0.726910  0.012169  0.308543  0.528447  0.982063
2013-01-02  0.223574  0.792436  0.213612  0.355721  0.435250
2013-01-03  0.786583  0.035750  0.276038  0.747099  0.821242
2013-01-04  0.144952  0.308997  0.751510  0.853518  0.203816
2013-01-05  0.139893  0.172160  0.202672  0.836874  0.165972
2013-01-06  0.175003  0.969984  0.889345  0.186474  0.074074
2013-01-07  0.681488  0.477574  0.213853  0.014540  0.341422
2013-01-08  0.338078  0.251049  0.727271  0.356723  0.719103
2013-01-09  0.318813  0.193021  0.359722  0.167650  0.990212
2013-01-10  0.221727  0.149285  0.656659  0.639777  0.360613
2013-01-11  0.997130  0.347977  0.045166  0.781557  0.085154
2013-01-12  0.852704  0.133926  0.256909  0.994200  0.421368
2013-01-13  0.183233  0.391373  0.780033  0.429919  0.405522
2013-01-14  0.356660  0.313288  0.550595  0.619666  0.729637
2013-01-15  0.090288  0.001321  0.961563  0.629908  0.234901

In [27]:
df

                   a         b         c         d
2013-01-01  0.528447  0.308543  0.012169  0.726910  0.982063
2013-01-02  0.355721  0.213612  0.792436  0.223574  0.435250
2013-01-03  0.747099  0.276038  0.035750  0.786583  0.821242
2013-01-04  0.853518  0.751510  0.308997  0.144952  0.203816
2013-01-05  0.836874  0.202672  0.172160  0.139893  0.165972
2013-01-06  0.186474  0.889345  0.969984  0.175003  0.074074
2013-01-07  0.014540  0.213853  0.477574  0.681488  0.341422
2013-01-08  0.356723  0.727271  0.251049  0.338078  0.719103
2013-01-09  0.167650  0.359722  0.193021  0.318813  0.990212
2013-01-10  0.639777  0.656659  0.149285  0.221727  0.360613
2013-01-11  0.781557  0.045166  0.347977  0.997130  0.085154
2013-01-12  0.994200  0.256909  0.133926  0.852704  0.421368
2013-01-13  0.429919  0.780033  0.391373  0.183233  0.405522
2013-01-14  0.619666  0.550595  0.313288  0.356660  0.729637
2013-01-15  0.629908  0.961563  0.001321  0.090288  0.234901

In [28]:
df.sort_values(by="a")

                   a         b         c         d
2013-01-07  0.014540  0.213853  0.477574  0.681488  0.341422
2013-01-09  0.167650  0.359722  0.193021  0.318813  0.990212
2013-01-06  0.186474  0.889345  0.969984  0.175003  0.074074
2013-01-02  0.355721  0.213612  0.792436  0.223574  0.435250
2013-01-08  0.356723  0.727271  0.251049  0.338078  0.719103
2013-01-13  0.429919  0.780033  0.391373  0.183233  0.405522
2013-01-01  0.528447  0.308543  0.012169  0.726910  0.982063
2013-01-14  0.619666  0.550595  0.313288  0.356660  0.729637
2013-01-15  0.629908  0.961563  0.001321  0.090288  0.234901
2013-01-10  0.639777  0.656659  0.149285  0.221727  0.360613
2013-01-03  0.747099  0.276038  0.035750  0.786583  0.821242
2013-01-11  0.781557  0.045166  0.347977  0.997130  0.085154
2013-01-05  0.836874  0.202672  0.172160  0.139893  0.165972
2013-01-04  0.853518  0.751510  0.308997  0.144952  0.203816
2013-01-12  0.994200  0.256909  0.133926  0.852704  0.421368

In [ ]:
what is getting

In [29]:
df

                   a         b         c         d
2013-01-01  0.528447  0.308543  0.012169  0.726910  0.982063
2013-01-02  0.355721  0.213612  0.792436  0.223574  0.435250
2013-01-03  0.747099  0.276038  0.035750  0.786583  0.821242
2013-01-04  0.853518  0.751510  0.308997  0.144952  0.203816
2013-01-05  0.836874  0.202672  0.172160  0.139893  0.165972
2013-01-06  0.186474  0.889345  0.969984  0.175003  0.074074
2013-01-07  0.014540  0.213853  0.477574  0.681488  0.341422
2013-01-08  0.356723  0.727271  0.251049  0.338078  0.719103
2013-01-09  0.167650  0.359722  0.193021  0.318813  0.990212
2013-01-10  0.639777  0.656659  0.149285  0.221727  0.360613
2013-01-11  0.781557  0.045166  0.347977  0.997130  0.085154
2013-01-12  0.994200  0.256909  0.133926  0.852704  0.421368
2013-01-13  0.429919  0.780033  0.391373  0.183233  0.405522
2013-01-14  0.619666  0.550595  0.313288  0.356660  0.729637
2013-01-15  0.629908  0.961563  0.001321  0.090288  0.234901

In [30]:
df[["a", "b"]]

                   a         b
2013-01-01  0.528447  0.308543
2013-01-02  0.355721  0.213612
2013-01-03  0.747099  0.276038
2013-01-04  0.853518  0.751510
2013-01-05  0.836874  0.202672
2013-01-06  0.186474  0.889345
2013-01-07  0.014540  0.213853
2013-01-08  0.356723  0.727271
2013-01-09  0.167650  0.359722
2013-01-10  0.639777  0.656659
2013-01-11  0.781557  0.045166
2013-01-12  0.994200  0.256909
2013-01-13  0.429919  0.780033
2013-01-14  0.619666  0.550595
2013-01-15  0.629908  0.961563

In [ ]:
what is indexes

In [31]:
df

                   a         b         c         d
2013-01-01  0.528447  0.308543  0.012169  0.726910  0.982063
2013-01-02  0.355721  0.213612  0.792436  0.223574  0.435250
2013-01-03  0.747099  0.276038  0.035750  0.786583  0.821242
2013-01-04  0.853518  0.751510  0.308997  0.144952  0.203816
2013-01-05  0.836874  0.202672  0.172160  0.139893  0.165972
2013-01-06  0.186474  0.889345  0.969984  0.175003  0.074074
2013-01-07  0.014540  0.213853  0.477574  0.681488  0.341422
2013-01-08  0.356723  0.727271  0.251049  0.338078  0.719103
2013-01-09  0.167650  0.359722  0.193021  0.318813  0.990212
2013-01-10  0.639777  0.656659  0.149285  0.221727  0.360613
2013-01-11  0.781557  0.045166  0.347977  0.997130  0.085154
2013-01-12  0.994200  0.256909  0.133926  0.852704  0.421368
2013-01-13  0.429919  0.780033  0.391373  0.183233  0.405522
2013-01-14  0.619666  0.550595  0.313288  0.356660  0.729637
2013-01-15  0.629908  0.961563  0.001321  0.090288  0.234901

In [32]:
df.shape

(15, 5)

In [ ]:
Data slices , mtlb apni marzi ka data kisi data mey sy nikalna, aur data slicing k liye ye 3 chizain use hotee hai 
(ilock, lock, aur index numbers)

In [ ]:
index koo lock karney k liye ye command dey

In [ ]:
df.ilok[3:5, 0:2]

In [44]:
import seaborn as sns 
kashti = sns.load_dataset("titanic") 
kashti

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [45]:
kashti.sample(100)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
594,0,2,male,37.0,1,0,26.0000,S,Second,man,True,NaN,Southampton,no,False
654,0,3,female,18.0,0,0,6.7500,Q,Third,woman,False,NaN,Queenstown,no,True
777,1,3,female,5.0,0,0,12.4750,S,Third,child,False,NaN,Southampton,yes,True
578,0,3,female,NaN,1,0,14.4583,C,Third,woman,False,NaN,Cherbourg,no,False
115,0,3,male,21.0,0,0,7.9250,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,0,3,male,9.0,4,2,31.3875,S,Third,child,False,NaN,Southampton,no,False
220,1,3,male,16.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,yes,True
56,1,2,female,21.0,0,0,10.5000,S,Second,woman,False,NaN,Southampton,yes,True
739,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
639,0,3,male,NaN,1,0,16.1000,S,Third,man,True,NaN,Southampton,no,False

In [ ]:
filter the data , using conditional operators

In [ ]:
df[df["A"] > 0]

In [46]:
kashti[kashti["age"]< 5]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
7,0,3,male,2.00,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
10,1,3,female,4.00,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
16,0,3,male,2.00,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
43,1,2,female,3.00,1,2,41.5792,C,Second,child,False,NaN,Cherbourg,yes,False
63,0,3,male,4.00,3,2,27.9000,S,Third,child,False,NaN,Southampton,no,False
78,1,2,male,0.83,0,2,29.0000,S,Second,child,False,NaN,Southampton,yes,False
119,0,3,female,2.00,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False
164,0,3,male,1.00,4,1,39.6875,S,Third,child,False,NaN,Southampton,no,False
171,0,3,male,4.00,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
172,1,3,female,1.00,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False
183,1,2,male,1.00,2,1,39.0000,S,Second,child,False,F,Southampton,yes,False
184,1,3,female,4.00,0,2,22.0250,S,Third,child,False,NaN,Southampton,yes,False
193,1,2,male,3.00,1,1,26.0000,S,Second,child,False,F,Southampton,yes,False
205,0,3,female,2.00,0,1,10.4625,S,Third,child,False,G,Southampton,no,False
261,1,3,male,3.00,4,2,31.3875,S,Third,child,False,NaN,Southampton,yes,False
297,0,1,female,2.00,1,2,151.5500,S,First,child,False,C,Southampton,no,False
305,1,1,male,0.92,1,2,151.5500,S,First,child,False,C,Southampton,yes,False
340,1,2,male,2.00,1,1,26.0000,S,Second,child,False,F,Southampton,yes,False
348,1,3,male,3.00,1,1,15.9000,S,Third,child,False,NaN,Southampton,yes,False
374,0,3,female,3.00,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
381,1,3,female,1.00,0,2,15.7417,C,Third,child,False,NaN,Cherbourg,yes,False
386,0,3,male,1.00,5,2,46.9000,S,Third,child,False,NaN,Southampton,no,False
407,1,2,male,3.00,1,1,18.7500,S,Second,child,False,NaN,Southampton,yes,False
445,1,1,male,4.00,0,2,81.8583,S,First,child,False,A,Southampton,yes,False
469,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
479,1,3,female,2.00,0,1,12.2875,S,Third,child,False,NaN,Southampton,yes,False
530,1,2,female,2.00,1,1,26.0000,S,Second,child,False,NaN,Southampton,yes,False
618,1,2,female,4.00,2,1,39.0000,S,Second,child,False,F,Southampton,yes,False
642,0,3,female,2.00,3,2,27.9000,S,Third,child,False,NaN,Southampton,no,False
644,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
691,1,3,female,4.00,0,1,13.4167,C,Third,child,False,NaN,Cherbourg,yes,False
750,1,2,female,4.00,1,1,23.0000,S,Second,child,False,NaN,Southampton,yes,False
755,1,2,male,0.67,1,1,14.5000,S,Second,child,False,NaN,Southampton,yes,False
788,1,3,male,1.00,1,2,20.5750,S,Third,child,False,NaN,Southampton,yes,False
803,1,3,male,0.42,0,1,8.5167,C,Third,child,False,NaN,Cherbourg,yes,False
824,0,3,male,2.00,4,1,39.6875,S,Third,child,False,NaN,Southampton,no,False
827,1,2,male,1.00,0,2,37.0042,C,Second,child,False,NaN,Cherbourg,yes,False
831,1,2,male,0.83,1,1,18.7500,S,Second,child,False,NaN,Southampton,yes,False
850,0,3,male,4.00,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False
869,1,3,male,4.00,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False

In [47]:
kashti[kashti["age"]< 1]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
78,1,2,male,0.83,0,2,29.0000,S,Second,child,False,NaN,Southampton,yes,False
305,1,1,male,0.92,1,2,151.5500,S,First,child,False,C,Southampton,yes,False
469,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
644,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
755,1,2,male,0.67,1,1,14.5000,S,Second,child,False,NaN,Southampton,yes,False
803,1,3,male,0.42,0,1,8.5167,C,Third,child,False,NaN,Cherbourg,yes,False
831,1,2,male,0.83,1,1,18.7500,S,Second,child,False,NaN,Southampton,yes,False

In [48]:
kashti[kashti["fare"]< 5]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
179,0,3,male,36.0,0,0,0.0000,S,Third,man,True,NaN,Southampton,no,True
263,0,1,male,40.0,0,0,0.0000,S,First,man,True,B,Southampton,no,True
271,1,3,male,25.0,0,0,0.0000,S,Third,man,True,NaN,Southampton,yes,True
277,0,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True
302,0,3,male,19.0,0,0,0.0000,S,Third,man,True,NaN,Southampton,no,True
378,0,3,male,20.0,0,0,4.0125,C,Third,man,True,NaN,Cherbourg,no,True
413,0,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True
466,0,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True
481,0,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True
597,0,3,male,49.0,0,0,0.0000,S,Third,man,True,NaN,Southampton,no,True
633,0,1,male,NaN,0,0,0.0000,S,First,man,True,NaN,Southampton,no,True
674,0,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True
732,0,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True
806,0,1,male,39.0,0,0,0.0000,S,First,man,True,A,Southampton,no,True
815,0,1,male,NaN,0,0,0.0000,S,First,man,True,B,Southampton,no,True
822,0,1,male,38.0,0,0,0.0000,S,First,man,True,NaN,Southampton,no,True