In [11]:
import pandas as pd

In [12]:
df = pd.read_excel(r"C:\Users\hp\Desktop\PRACTICE\CATTLE.xlsx")

In [13]:
df.head()

,ID,TagNumber,Breed,Gender,BirthDate,Weight,Color,IsPregnant,MotherID,FatherID
0,1,T001,Holstein,Female,2022-01-12,500,Black and white,1,NaN,NaN
1,2,T002,Angus,Male,2021-05-20,600,Black,0,NaN,NaN
2,3,T003,Hereford,Female,2022-03-15,550,Red and white,1,1.0,2.0
3,4,T004,Simmental,Male,2021-11-08,650,Red,0,NaN,NaN
4,5,T005,Charolais,Female,2022-02-28,580,White,1,3.0,4.0

In [14]:
df.tail

<bound method NDFrame.tail of     ID TagNumber        Breed  Gender  BirthDate  Weight            Color  \
0    1      T001     Holstein  Female 2022-01-12     500  Black and white
1    2      T002        Angus    Male 2021-05-20     600            Black
2    3      T003     Hereford  Female 2022-03-15     550    Red and white
3    4      T004    Simmental    Male 2021-11-08     650              Red
4    5      T005    Charolais  Female 2022-02-28     580            White
5    6      T006     Limousin    Male 2021-08-18     620           Yellow
6    7      T007     Gelbvieh  Female 2022-06-01     570            Brown
7    8      T008    Shorthorn    Male 2021-12-25     630    Red and white
8    9      T009      Brahman  Female 2022-04-10     590             Gray
9   10      T010  Maine-Anjou    Male 2021-09-05     640    Red and white
10  11      T011     Chianina  Female 2022-07-22     560            White
11  12      T012       Salers    Male 2021-10-15     610              Tan
12  13      T013    Pinzgauer  Female 2022-05-03     580    Red and white
13  14      T014     Galloway    Male 2021-11-30     620            Black
14  15      T015   Tarentaise  Female 2022-03-18     570              Tan
15  16      T016       Belted    Male 2021-08-22     630  Black and white
16  17      T017       Dexter  Female 2022-06-12     550            Black
17  18      T018     Guernsey    Male 2021-12-08     610             Fawn
18  19      T019       Jersey  Female 2022-04-25     560             Fawn
19  20      T020      Milking    Male 2021-09-19     620            White
20  21      T021    Shorthorn  Female 2022-07-01     580    Red and white
21  22      T022     Hereford    Male 2021-10-28     640    Red and white
22  23      T023        Angus  Female 2022-05-12     570            Black
23  24      T024    Simmental    Male 2021-11-03     630              Red
24  25      T025    Charolais  Female 2022-03-08     590            White
25  26      T026     Limousin    Male 2021-08-30     640           Yellow
26  27      T027     Gelbvieh  Female 2022-06-18     560            Brown
27  28      T028      Brahman    Male 2021-12-12     620             Gray
28  29      T029  Maine-Anjou  Female 2022-04-22     580    Red and white
29  30      T030     Chianina    Male 2021-09-11     630            White
30  31      T031       Salers  Female 2022-07-29     570              Tan
31  32      T032    Pinzgauer    Male 2021-10-22     640    Red and white
32  33      T033     Galloway  Female 2022-05-15     560            Black
33  34      T034   Tarentaise    Male 2021-12-05     620              Tan
34  35      T035       Belted  Female 2022-03-25     580  Black and white
35  36      T036       Dexter    Male 2021-08-29     630            Black
36  37      T037     Guernsey  Female 2022-06-20     550             Fawn
37  38      T038       Jersey    Male 2021-12-15     610             Fawn
38  39      T039      Milking  Female 2022-05-01     560            White
39  40      T040    Shorthorn    Male 2021-09-26     620    Red and white
40  41      T041     Hereford  Female 2022-07-08     580    Red and white
41  42      T042        Angus    Male 2021-11-10     640            Black
42  43      T043    Simmental  Female 2022-05-20     570              Red
43  44      T044    Charolais    Male 2021-11-18     630            White
44  45      T045     Limousin  Female 2022-03-15     590           Yellow
45  46      T046     Gelbvieh    Male 2021-09-02     640            Brown
46  47      T047      Brahman  Female 2022-06-25     560             Gray
47  48      T048  Maine-Anjou    Male 2021-12-22     620    Red and white

    IsPregnant  MotherID  FatherID
0            1       NaN       NaN
1            0       NaN       NaN
2            1       1.0       2.0
3            0       NaN       NaN
4            1       3.0       4.0
5            0       NaN       NaN
6            1       5.0       6.0
7            0       NaN       NaN
8            1       7.0       8.0
9            0       NaN       NaN
10           1       9.0      10.0
11           0       NaN       NaN
12           1      11.0      12.0
13           0       NaN       NaN
14           1      13.0      14.0
15           0       NaN       NaN
16           1      15.0      16.0
17           0       NaN       NaN
18           1      17.0      18.0
19           0       NaN       NaN
20           1      19.0      20.0
21           0       NaN       NaN
22           1      21.0      22.0
23           0       NaN       NaN
24           1      23.0      24.0
25           0       NaN       NaN
26           1      25.0      26.0
27           0       NaN       NaN
28           1      27.0      28.0
29           0       NaN       NaN
30           1      29.0      30.0
31           0       NaN       NaN
32           1      31.0      32.0
33           0       NaN       NaN
34           1      33.0      34.0
35           0       NaN       NaN
36           1      35.0      36.0
37           0       NaN       NaN
38           1      37.0      38.0
39           0       NaN       NaN
40           1      39.0      40.0
41           0       NaN       NaN
42           1      41.0      42.0
43           0       NaN       NaN
44           1      43.0      44.0
45           0       NaN       NaN
46           1      45.0      46.0
47           0       NaN       NaN  >

In [15]:
df.shape

(48, 10)

In [16]:
df.head(10)

,ID,TagNumber,Breed,Gender,BirthDate,Weight,Color,IsPregnant,MotherID,FatherID
0,1,T001,Holstein,Female,2022-01-12,500,Black and white,1,NaN,NaN
1,2,T002,Angus,Male,2021-05-20,600,Black,0,NaN,NaN
2,3,T003,Hereford,Female,2022-03-15,550,Red and white,1,1.0,2.0
3,4,T004,Simmental,Male,2021-11-08,650,Red,0,NaN,NaN
4,5,T005,Charolais,Female,2022-02-28,580,White,1,3.0,4.0
5,6,T006,Limousin,Male,2021-08-18,620,Yellow,0,NaN,NaN
6,7,T007,Gelbvieh,Female,2022-06-01,570,Brown,1,5.0,6.0
7,8,T008,Shorthorn,Male,2021-12-25,630,Red and white,0,NaN,NaN
8,9,T009,Brahman,Female,2022-04-10,590,Gray,1,7.0,8.0
9,10,T010,Maine-Anjou,Male,2021-09-05,640,Red and white,0,NaN,NaN

In [17]:
df.tail(6)

,ID,TagNumber,Breed,Gender,BirthDate,Weight,Color,IsPregnant,MotherID,FatherID
42,43,T043,Simmental,Female,2022-05-20,570,Red,1,41.0,42.0
43,44,T044,Charolais,Male,2021-11-18,630,White,0,NaN,NaN
44,45,T045,Limousin,Female,2022-03-15,590,Yellow,1,43.0,44.0
45,46,T046,Gelbvieh,Male,2021-09-02,640,Brown,0,NaN,NaN
46,47,T047,Brahman,Female,2022-06-25,560,Gray,1,45.0,46.0
47,48,T048,Maine-Anjou,Male,2021-12-22,620,Red and white,0,NaN,NaN

In [18]:
import pandas as pd

In [19]:
df = pd.read_excel(r"C:\Users\hp\Desktop\PRACTICE\CATTLE.xlsx")

In [20]:
df.head()

,ID,TagNumber,Breed,Gender,BirthDate,Weight,Color,IsPregnant,MotherID,FatherID
0,1,T001,Holstein,Female,2022-01-12,500,Black and white,1,NaN,NaN
1,2,T002,Angus,Male,2021-05-20,600,Black,0,NaN,NaN
2,3,T003,Hereford,Female,2022-03-15,550,Red and white,1,1.0,2.0
3,4,T004,Simmental,Male,2021-11-08,650,Red,0,NaN,NaN
4,5,T005,Charolais,Female,2022-02-28,580,White,1,3.0,4.0

view data frames in python using pandas

In [22]:
df.head

<bound method NDFrame.head of     ID TagNumber        Breed  Gender  BirthDate  Weight            Color  \
0    1      T001     Holstein  Female 2022-01-12     500  Black and white
1    2      T002        Angus    Male 2021-05-20     600            Black
2    3      T003     Hereford  Female 2022-03-15     550    Red and white
3    4      T004    Simmental    Male 2021-11-08     650              Red
4    5      T005    Charolais  Female 2022-02-28     580            White
5    6      T006     Limousin    Male 2021-08-18     620           Yellow
6    7      T007     Gelbvieh  Female 2022-06-01     570            Brown
7    8      T008    Shorthorn    Male 2021-12-25     630    Red and white
8    9      T009      Brahman  Female 2022-04-10     590             Gray
9   10      T010  Maine-Anjou    Male 2021-09-05     640    Red and white
10  11      T011     Chianina  Female 2022-07-22     560            White
11  12      T012       Salers    Male 2021-10-15     610              Tan
12  13      T013    Pinzgauer  Female 2022-05-03     580    Red and white
13  14      T014     Galloway    Male 2021-11-30     620            Black
14  15      T015   Tarentaise  Female 2022-03-18     570              Tan
15  16      T016       Belted    Male 2021-08-22     630  Black and white
16  17      T017       Dexter  Female 2022-06-12     550            Black
17  18      T018     Guernsey    Male 2021-12-08     610             Fawn
18  19      T019       Jersey  Female 2022-04-25     560             Fawn
19  20      T020      Milking    Male 2021-09-19     620            White
20  21      T021    Shorthorn  Female 2022-07-01     580    Red and white
21  22      T022     Hereford    Male 2021-10-28     640    Red and white
22  23      T023        Angus  Female 2022-05-12     570            Black
23  24      T024    Simmental    Male 2021-11-03     630              Red
24  25      T025    Charolais  Female 2022-03-08     590            White
25  26      T026     Limousin    Male 2021-08-30     640           Yellow
26  27      T027     Gelbvieh  Female 2022-06-18     560            Brown
27  28      T028      Brahman    Male 2021-12-12     620             Gray
28  29      T029  Maine-Anjou  Female 2022-04-22     580    Red and white
29  30      T030     Chianina    Male 2021-09-11     630            White
30  31      T031       Salers  Female 2022-07-29     570              Tan
31  32      T032    Pinzgauer    Male 2021-10-22     640    Red and white
32  33      T033     Galloway  Female 2022-05-15     560            Black
33  34      T034   Tarentaise    Male 2021-12-05     620              Tan
34  35      T035       Belted  Female 2022-03-25     580  Black and white
35  36      T036       Dexter    Male 2021-08-29     630            Black
36  37      T037     Guernsey  Female 2022-06-20     550             Fawn
37  38      T038       Jersey    Male 2021-12-15     610             Fawn
38  39      T039      Milking  Female 2022-05-01     560            White
39  40      T040    Shorthorn    Male 2021-09-26     620    Red and white
40  41      T041     Hereford  Female 2022-07-08     580    Red and white
41  42      T042        Angus    Male 2021-11-10     640            Black
42  43      T043    Simmental  Female 2022-05-20     570              Red
43  44      T044    Charolais    Male 2021-11-18     630            White
44  45      T045     Limousin  Female 2022-03-15     590           Yellow
45  46      T046     Gelbvieh    Male 2021-09-02     640            Brown
46  47      T047      Brahman  Female 2022-06-25     560             Gray
47  48      T048  Maine-Anjou    Male 2021-12-22     620    Red and white

    IsPregnant  MotherID  FatherID
0            1       NaN       NaN
1            0       NaN       NaN
2            1       1.0       2.0
3            0       NaN       NaN
4            1       3.0       4.0
5            0       NaN       NaN
6            1       5.0       6.0
7            0       NaN       NaN
8            1       7.0       8.0
9            0       NaN       NaN
10           1       9.0      10.0
11           0       NaN       NaN
12           1      11.0      12.0
13           0       NaN       NaN
14           1      13.0      14.0
15           0       NaN       NaN
16           1      15.0      16.0
17           0       NaN       NaN
18           1      17.0      18.0
19           0       NaN       NaN
20           1      19.0      20.0
21           0       NaN       NaN
22           1      21.0      22.0
23           0       NaN       NaN
24           1      23.0      24.0
25           0       NaN       NaN
26           1      25.0      26.0
27           0       NaN       NaN
28           1      27.0      28.0
29           0       NaN       NaN
30           1      29.0      30.0
31           0       NaN       NaN
32           1      31.0      32.0
33           0       NaN       NaN
34           1      33.0      34.0
35           0       NaN       NaN
36           1      35.0      36.0
37           0       NaN       NaN
38           1      37.0      38.0
39           0       NaN       NaN
40           1      39.0      40.0
41           0       NaN       NaN
42           1      41.0      42.0
43           0       NaN       NaN
44           1      43.0      44.0
45           0       NaN       NaN
46           1      45.0      46.0
47           0       NaN       NaN  >

In [23]:
df.tail

<bound method NDFrame.tail of     ID TagNumber        Breed  Gender  BirthDate  Weight            Color  \
0    1      T001     Holstein  Female 2022-01-12     500  Black and white
1    2      T002        Angus    Male 2021-05-20     600            Black
2    3      T003     Hereford  Female 2022-03-15     550    Red and white
3    4      T004    Simmental    Male 2021-11-08     650              Red
4    5      T005    Charolais  Female 2022-02-28     580            White
5    6      T006     Limousin    Male 2021-08-18     620           Yellow
6    7      T007     Gelbvieh  Female 2022-06-01     570            Brown
7    8      T008    Shorthorn    Male 2021-12-25     630    Red and white
8    9      T009      Brahman  Female 2022-04-10     590             Gray
9   10      T010  Maine-Anjou    Male 2021-09-05     640    Red and white
10  11      T011     Chianina  Female 2022-07-22     560            White
11  12      T012       Salers    Male 2021-10-15     610              Tan
12  13      T013    Pinzgauer  Female 2022-05-03     580    Red and white
13  14      T014     Galloway    Male 2021-11-30     620            Black
14  15      T015   Tarentaise  Female 2022-03-18     570              Tan
15  16      T016       Belted    Male 2021-08-22     630  Black and white
16  17      T017       Dexter  Female 2022-06-12     550            Black
17  18      T018     Guernsey    Male 2021-12-08     610             Fawn
18  19      T019       Jersey  Female 2022-04-25     560             Fawn
19  20      T020      Milking    Male 2021-09-19     620            White
20  21      T021    Shorthorn  Female 2022-07-01     580    Red and white
21  22      T022     Hereford    Male 2021-10-28     640    Red and white
22  23      T023        Angus  Female 2022-05-12     570            Black
23  24      T024    Simmental    Male 2021-11-03     630              Red
24  25      T025    Charolais  Female 2022-03-08     590            White
25  26      T026     Limousin    Male 2021-08-30     640           Yellow
26  27      T027     Gelbvieh  Female 2022-06-18     560            Brown
27  28      T028      Brahman    Male 2021-12-12     620             Gray
28  29      T029  Maine-Anjou  Female 2022-04-22     580    Red and white
29  30      T030     Chianina    Male 2021-09-11     630            White
30  31      T031       Salers  Female 2022-07-29     570              Tan
31  32      T032    Pinzgauer    Male 2021-10-22     640    Red and white
32  33      T033     Galloway  Female 2022-05-15     560            Black
33  34      T034   Tarentaise    Male 2021-12-05     620              Tan
34  35      T035       Belted  Female 2022-03-25     580  Black and white
35  36      T036       Dexter    Male 2021-08-29     630            Black
36  37      T037     Guernsey  Female 2022-06-20     550             Fawn
37  38      T038       Jersey    Male 2021-12-15     610             Fawn
38  39      T039      Milking  Female 2022-05-01     560            White
39  40      T040    Shorthorn    Male 2021-09-26     620    Red and white
40  41      T041     Hereford  Female 2022-07-08     580    Red and white
41  42      T042        Angus    Male 2021-11-10     640            Black
42  43      T043    Simmental  Female 2022-05-20     570              Red
43  44      T044    Charolais    Male 2021-11-18     630            White
44  45      T045     Limousin  Female 2022-03-15     590           Yellow
45  46      T046     Gelbvieh    Male 2021-09-02     640            Brown
46  47      T047      Brahman  Female 2022-06-25     560             Gray
47  48      T048  Maine-Anjou    Male 2021-12-22     620    Red and white

    IsPregnant  MotherID  FatherID
0            1       NaN       NaN
1            0       NaN       NaN
2            1       1.0       2.0
3            0       NaN       NaN
4            1       3.0       4.0
5            0       NaN       NaN
6            1       5.0       6.0
7            0       NaN       NaN
8            1       7.0       8.0
9            0       NaN       NaN
10           1       9.0      10.0
11           0       NaN       NaN
12           1      11.0      12.0
13           0       NaN       NaN
14           1      13.0      14.0
15           0       NaN       NaN
16           1      15.0      16.0
17           0       NaN       NaN
18           1      17.0      18.0
19           0       NaN       NaN
20           1      19.0      20.0
21           0       NaN       NaN
22           1      21.0      22.0
23           0       NaN       NaN
24           1      23.0      24.0
25           0       NaN       NaN
26           1      25.0      26.0
27           0       NaN       NaN
28           1      27.0      28.0
29           0       NaN       NaN
30           1      29.0      30.0
31           0       NaN       NaN
32           1      31.0      32.0
33           0       NaN       NaN
34           1      33.0      34.0
35           0       NaN       NaN
36           1      35.0      36.0
37           0       NaN       NaN
38           1      37.0      38.0
39           0       NaN       NaN
40           1      39.0      40.0
41           0       NaN       NaN
42           1      41.0      42.0
43           0       NaN       NaN
44           1      43.0      44.0
45           0       NaN       NaN
46           1      45.0      46.0
47           0       NaN       NaN  >

In [24]:
df.shape

(48, 10)

In [25]:
df.info

<bound method DataFrame.info of     ID TagNumber        Breed  Gender  BirthDate  Weight            Color  \
0    1      T001     Holstein  Female 2022-01-12     500  Black and white
1    2      T002        Angus    Male 2021-05-20     600            Black
2    3      T003     Hereford  Female 2022-03-15     550    Red and white
3    4      T004    Simmental    Male 2021-11-08     650              Red
4    5      T005    Charolais  Female 2022-02-28     580            White
5    6      T006     Limousin    Male 2021-08-18     620           Yellow
6    7      T007     Gelbvieh  Female 2022-06-01     570            Brown
7    8      T008    Shorthorn    Male 2021-12-25     630    Red and white
8    9      T009      Brahman  Female 2022-04-10     590             Gray
9   10      T010  Maine-Anjou    Male 2021-09-05     640    Red and white
10  11      T011     Chianina  Female 2022-07-22     560            White
11  12      T012       Salers    Male 2021-10-15     610              Tan
12  13      T013    Pinzgauer  Female 2022-05-03     580    Red and white
13  14      T014     Galloway    Male 2021-11-30     620            Black
14  15      T015   Tarentaise  Female 2022-03-18     570              Tan
15  16      T016       Belted    Male 2021-08-22     630  Black and white
16  17      T017       Dexter  Female 2022-06-12     550            Black
17  18      T018     Guernsey    Male 2021-12-08     610             Fawn
18  19      T019       Jersey  Female 2022-04-25     560             Fawn
19  20      T020      Milking    Male 2021-09-19     620            White
20  21      T021    Shorthorn  Female 2022-07-01     580    Red and white
21  22      T022     Hereford    Male 2021-10-28     640    Red and white
22  23      T023        Angus  Female 2022-05-12     570            Black
23  24      T024    Simmental    Male 2021-11-03     630              Red
24  25      T025    Charolais  Female 2022-03-08     590            White
25  26      T026     Limousin    Male 2021-08-30     640           Yellow
26  27      T027     Gelbvieh  Female 2022-06-18     560            Brown
27  28      T028      Brahman    Male 2021-12-12     620             Gray
28  29      T029  Maine-Anjou  Female 2022-04-22     580    Red and white
29  30      T030     Chianina    Male 2021-09-11     630            White
30  31      T031       Salers  Female 2022-07-29     570              Tan
31  32      T032    Pinzgauer    Male 2021-10-22     640    Red and white
32  33      T033     Galloway  Female 2022-05-15     560            Black
33  34      T034   Tarentaise    Male 2021-12-05     620              Tan
34  35      T035       Belted  Female 2022-03-25     580  Black and white
35  36      T036       Dexter    Male 2021-08-29     630            Black
36  37      T037     Guernsey  Female 2022-06-20     550             Fawn
37  38      T038       Jersey    Male 2021-12-15     610             Fawn
38  39      T039      Milking  Female 2022-05-01     560            White
39  40      T040    Shorthorn    Male 2021-09-26     620    Red and white
40  41      T041     Hereford  Female 2022-07-08     580    Red and white
41  42      T042        Angus    Male 2021-11-10     640            Black
42  43      T043    Simmental  Female 2022-05-20     570              Red
43  44      T044    Charolais    Male 2021-11-18     630            White
44  45      T045     Limousin  Female 2022-03-15     590           Yellow
45  46      T046     Gelbvieh    Male 2021-09-02     640            Brown
46  47      T047      Brahman  Female 2022-06-25     560             Gray
47  48      T048  Maine-Anjou    Male 2021-12-22     620    Red and white

    IsPregnant  MotherID  FatherID
0            1       NaN       NaN
1            0       NaN       NaN
2            1       1.0       2.0
3            0       NaN       NaN
4            1       3.0       4.0
5            0       NaN       NaN
6            1       5.0       6.0
7            0       NaN       NaN
8            1       7.0       8.0
9            0       NaN       NaN
10           1       9.0      10.0
11           0       NaN       NaN
12           1      11.0      12.0
13           0       NaN       NaN
14           1      13.0      14.0
15           0       NaN       NaN
16           1      15.0      16.0
17           0       NaN       NaN
18           1      17.0      18.0
19           0       NaN       NaN
20           1      19.0      20.0
21           0       NaN       NaN
22           1      21.0      22.0
23           0       NaN       NaN
24           1      23.0      24.0
25           0       NaN       NaN
26           1      25.0      26.0
27           0       NaN       NaN
28           1      27.0      28.0
29           0       NaN       NaN
30           1      29.0      30.0
31           0       NaN       NaN
32           1      31.0      32.0
33           0       NaN       NaN
34           1      33.0      34.0
35           0       NaN       NaN
36           1      35.0      36.0
37           0       NaN       NaN
38           1      37.0      38.0
39           0       NaN       NaN
40           1      39.0      40.0
41           0       NaN       NaN
42           1      41.0      42.0
43           0       NaN       NaN
44           1      43.0      44.0
45           0       NaN       NaN
46           1      45.0      46.0
47           0       NaN       NaN  >

In [26]:
df.index

RangeIndex(start=0, stop=48, step=1)

In [ ]:
df.coloums()

In [30]:
df.describe()

          ID            BirthDate     Weight  IsPregnant  MotherID  FatherID
count  48.00                   48   48.00000   48.000000  23.00000  23.00000
mean   24.50  2022-01-25 04:30:00  596.87500    0.500000  23.00000  24.00000
min     1.00  2021-05-20 00:00:00  500.00000    0.000000   1.00000   2.00000
25%    12.75  2021-10-26 12:00:00  570.00000    0.000000  12.00000  13.00000
50%    24.50  2022-01-03 00:00:00  595.00000    0.500000  23.00000  24.00000
75%    36.25  2022-05-05 06:00:00  630.00000    1.000000  34.00000  35.00000
max    48.00  2022-07-29 00:00:00  650.00000    1.000000  45.00000  46.00000
std    14.00                  NaN   34.03104    0.505291  13.56466  13.56466

In [32]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
ID,1,2,3,4,5,6,7,8,9,10,...,39,40,41,42,43,44,45,46,47,48
TagNumber,T001,T002,T003,T004,T005,T006,T007,T008,T009,T010,...,T039,T040,T041,T042,T043,T044,T045,T046,T047,T048
Breed,Holstein,Angus,Hereford,Simmental,Charolais,Limousin,Gelbvieh,Shorthorn,Brahman,Maine-Anjou,...,Milking,Shorthorn,Hereford,Angus,Simmental,Charolais,Limousin,Gelbvieh,Brahman,Maine-Anjou
Gender,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,...,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male
BirthDate,2022-01-12 00:00:00,2021-05-20 00:00:00,2022-03-15 00:00:00,2021-11-08 00:00:00,2022-02-28 00:00:00,2021-08-18 00:00:00,2022-06-01 00:00:00,2021-12-25 00:00:00,2022-04-10 00:00:00,2021-09-05 00:00:00,...,2022-05-01 00:00:00,2021-09-26 00:00:00,2022-07-08 00:00:00,2021-11-10 00:00:00,2022-05-20 00:00:00,2021-11-18 00:00:00,2022-03-15 00:00:00,2021-09-02 00:00:00,2022-06-25 00:00:00,2021-12-22 00:00:00
Weight,500,600,550,650,580,620,570,630,590,640,...,560,620,580,640,570,630,590,640,560,620
Color,Black and white,Black,Red and white,Red,White,Yellow,Brown,Red and white,Gray,Red and white,...,White,Red and white,Red and white,Black,Red,White,Yellow,Brown,Gray,Red and white
IsPregnant,1,0,1,0,1,0,1,0,1,0,...,1,0,1,0,1,0,1,0,1,0
MotherID,NaN,NaN,1.0,NaN,3.0,NaN,5.0,NaN,7.0,NaN,...,37.0,NaN,39.0,NaN,41.0,NaN,43.0,NaN,45.0,NaN
FatherID,NaN,NaN,2.0,NaN,4.0,NaN,6.0,NaN,8.0,NaN,...,38.0,NaN,40.0,NaN,42.0,NaN,44.0,NaN,46.0,NaN

In [34]:
df.sort_index()

,ID,TagNumber,Breed,Gender,BirthDate,Weight,Color,IsPregnant,MotherID,FatherID
0,1,T001,Holstein,Female,2022-01-12,500,Black and white,1,NaN,NaN
1,2,T002,Angus,Male,2021-05-20,600,Black,0,NaN,NaN
2,3,T003,Hereford,Female,2022-03-15,550,Red and white,1,1.0,2.0
3,4,T004,Simmental,Male,2021-11-08,650,Red,0,NaN,NaN
4,5,T005,Charolais,Female,2022-02-28,580,White,1,3.0,4.0
5,6,T006,Limousin,Male,2021-08-18,620,Yellow,0,NaN,NaN
6,7,T007,Gelbvieh,Female,2022-06-01,570,Brown,1,5.0,6.0
7,8,T008,Shorthorn,Male,2021-12-25,630,Red and white,0,NaN,NaN
8,9,T009,Brahman,Female,2022-04-10,590,Gray,1,7.0,8.0
9,10,T010,Maine-Anjou,Male,2021-09-05,640,Red and white,0,NaN,NaN
10,11,T011,Chianina,Female,2022-07-22,560,White,1,9.0,10.0
11,12,T012,Salers,Male,2021-10-15,610,Tan,0,NaN,NaN
12,13,T013,Pinzgauer,Female,2022-05-03,580,Red and white,1,11.0,12.0
13,14,T014,Galloway,Male,2021-11-30,620,Black,0,NaN,NaN
14,15,T015,Tarentaise,Female,2022-03-18,570,Tan,1,13.0,14.0
15,16,T016,Belted,Male,2021-08-22,630,Black and white,0,NaN,NaN
16,17,T017,Dexter,Female,2022-06-12,550,Black,1,15.0,16.0
17,18,T018,Guernsey,Male,2021-12-08,610,Fawn,0,NaN,NaN
18,19,T019,Jersey,Female,2022-04-25,560,Fawn,1,17.0,18.0
19,20,T020,Milking,Male,2021-09-19,620,White,0,NaN,NaN
20,21,T021,Shorthorn,Female,2022-07-01,580,Red and white,1,19.0,20.0
21,22,T022,Hereford,Male,2021-10-28,640,Red and white,0,NaN,NaN
22,23,T023,Angus,Female,2022-05-12,570,Black,1,21.0,22.0
23,24,T024,Simmental,Male,2021-11-03,630,Red,0,NaN,NaN
24,25,T025,Charolais,Female,2022-03-08,590,White,1,23.0,24.0
25,26,T026,Limousin,Male,2021-08-30,640,Yellow,0,NaN,NaN
26,27,T027,Gelbvieh,Female,2022-06-18,560,Brown,1,25.0,26.0
27,28,T028,Brahman,Male,2021-12-12,620,Gray,0,NaN,NaN
28,29,T029,Maine-Anjou,Female,2022-04-22,580,Red and white,1,27.0,28.0
29,30,T030,Chianina,Male,2021-09-11,630,White,0,NaN,NaN
30,31,T031,Salers,Female,2022-07-29,570,Tan,1,29.0,30.0
31,32,T032,Pinzgauer,Male,2021-10-22,640,Red and white,0,NaN,NaN
32,33,T033,Galloway,Female,2022-05-15,560,Black,1,31.0,32.0
33,34,T034,Tarentaise,Male,2021-12-05,620,Tan,0,NaN,NaN
34,35,T035,Belted,Female,2022-03-25,580,Black and white,1,33.0,34.0
35,36,T036,Dexter,Male,2021-08-29,630,Black,0,NaN,NaN
36,37,T037,Guernsey,Female,2022-06-20,550,Fawn,1,35.0,36.0
37,38,T038,Jersey,Male,2021-12-15,610,Fawn,0,NaN,NaN
38,39,T039,Milking,Female,2022-05-01,560,White,1,37.0,38.0
39,40,T040,Shorthorn,Male,2021-09-26,620,Red and white,0,NaN,NaN
40,41,T041,Hereford,Female,2022-07-08,580,Red and white,1,39.0,40.0
41,42,T042,Angus,Male,2021-11-10,640,Black,0,NaN,NaN
42,43,T043,Simmental,Female,2022-05-20,570,Red,1,41.0,42.0
43,44,T044,Charolais,Male,2021-11-18,630,White,0,NaN,NaN
44,45,T045,Limousin,Female,2022-03-15,590,Yellow,1,43.0,44.0
45,46,T046,Gelbvieh,Male,2021-09-02,640,Brown,0,NaN,NaN
46,47,T047,Brahman,Female,2022-06-25,560,Gray,1,45.0,46.0
47,48,T048,Maine-Anjou,Male,2021-12-22,620,Red and white,0,NaN,NaN

In [35]:
df.sort_index(ascending=False)

,ID,TagNumber,Breed,Gender,BirthDate,Weight,Color,IsPregnant,MotherID,FatherID
47,48,T048,Maine-Anjou,Male,2021-12-22,620,Red and white,0,NaN,NaN
46,47,T047,Brahman,Female,2022-06-25,560,Gray,1,45.0,46.0
45,46,T046,Gelbvieh,Male,2021-09-02,640,Brown,0,NaN,NaN
44,45,T045,Limousin,Female,2022-03-15,590,Yellow,1,43.0,44.0
43,44,T044,Charolais,Male,2021-11-18,630,White,0,NaN,NaN
42,43,T043,Simmental,Female,2022-05-20,570,Red,1,41.0,42.0
41,42,T042,Angus,Male,2021-11-10,640,Black,0,NaN,NaN
40,41,T041,Hereford,Female,2022-07-08,580,Red and white,1,39.0,40.0
39,40,T040,Shorthorn,Male,2021-09-26,620,Red and white,0,NaN,NaN
38,39,T039,Milking,Female,2022-05-01,560,White,1,37.0,38.0
37,38,T038,Jersey,Male,2021-12-15,610,Fawn,0,NaN,NaN
36,37,T037,Guernsey,Female,2022-06-20,550,Fawn,1,35.0,36.0
35,36,T036,Dexter,Male,2021-08-29,630,Black,0,NaN,NaN
34,35,T035,Belted,Female,2022-03-25,580,Black and white,1,33.0,34.0
33,34,T034,Tarentaise,Male,2021-12-05,620,Tan,0,NaN,NaN
32,33,T033,Galloway,Female,2022-05-15,560,Black,1,31.0,32.0
31,32,T032,Pinzgauer,Male,2021-10-22,640,Red and white,0,NaN,NaN
30,31,T031,Salers,Female,2022-07-29,570,Tan,1,29.0,30.0
29,30,T030,Chianina,Male,2021-09-11,630,White,0,NaN,NaN
28,29,T029,Maine-Anjou,Female,2022-04-22,580,Red and white,1,27.0,28.0
27,28,T028,Brahman,Male,2021-12-12,620,Gray,0,NaN,NaN
26,27,T027,Gelbvieh,Female,2022-06-18,560,Brown,1,25.0,26.0
25,26,T026,Limousin,Male,2021-08-30,640,Yellow,0,NaN,NaN
24,25,T025,Charolais,Female,2022-03-08,590,White,1,23.0,24.0
23,24,T024,Simmental,Male,2021-11-03,630,Red,0,NaN,NaN
22,23,T023,Angus,Female,2022-05-12,570,Black,1,21.0,22.0
21,22,T022,Hereford,Male,2021-10-28,640,Red and white,0,NaN,NaN
20,21,T021,Shorthorn,Female,2022-07-01,580,Red and white,1,19.0,20.0
19,20,T020,Milking,Male,2021-09-19,620,White,0,NaN,NaN
18,19,T019,Jersey,Female,2022-04-25,560,Fawn,1,17.0,18.0
17,18,T018,Guernsey,Male,2021-12-08,610,Fawn,0,NaN,NaN
16,17,T017,Dexter,Female,2022-06-12,550,Black,1,15.0,16.0
15,16,T016,Belted,Male,2021-08-22,630,Black and white,0,NaN,NaN
14,15,T015,Tarentaise,Female,2022-03-18,570,Tan,1,13.0,14.0
13,14,T014,Galloway,Male,2021-11-30,620,Black,0,NaN,NaN
12,13,T013,Pinzgauer,Female,2022-05-03,580,Red and white,1,11.0,12.0
11,12,T012,Salers,Male,2021-10-15,610,Tan,0,NaN,NaN
10,11,T011,Chianina,Female,2022-07-22,560,White,1,9.0,10.0
9,10,T010,Maine-Anjou,Male,2021-09-05,640,Red and white,0,NaN,NaN
8,9,T009,Brahman,Female,2022-04-10,590,Gray,1,7.0,8.0
7,8,T008,Shorthorn,Male,2021-12-25,630,Red and white,0,NaN,NaN
6,7,T007,Gelbvieh,Female,2022-06-01,570,Brown,1,5.0,6.0
5,6,T006,Limousin,Male,2021-08-18,620,Yellow,0,NaN,NaN
4,5,T005,Charolais,Female,2022-02-28,580,White,1,3.0,4.0
3,4,T004,Simmental,Male,2021-11-08,650,Red,0,NaN,NaN
2,3,T003,Hereford,Female,2022-03-15,550,Red and white,1,1.0,2.0
1,2,T002,Angus,Male,2021-05-20,600,Black,0,NaN,NaN
0,1,T001,Holstein,Female,2022-01-12,500,Black and white,1,NaN,NaN

In [ ]:
df.sort_values

In [ ]:
pd.show_v